services:
  - type: web
    name: aimenu-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    plan: free

  - type: web
    name: aimenu-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
    staticPublishPath: "./frontend"
    envVars:
      - key: REACT_APP_API_URL
        value: https://aimenu-backend.onrender.com  # This will be updated after backend deploys
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
